import dictionary from "./curse-dictionary.json" with { type: "json" };

type Bilingual = { en: string; ru: string };

export const curseLevels = {
  mild: { en: "Mild", ru: "Мягкое" },
  rude: { en: "Rude", ru: "Грубое" },
  obscene: { en: "Obscene · mat", ru: "Нецензурное · мат" },
};
export const curseTypes = {
  exclamation: { en: "Exclamations", ru: "Восклицания" },
  insult: { en: "Insults", ru: "Оскорбления" },
  expression: { en: "Words & phrases", ru: "Слова и выражения" },
  verb: { en: "Verbs", ru: "Глаголы" },
};
export type CurseLevel = keyof typeof curseLevels;
export type CurseType = keyof typeof curseTypes;
export interface CurseEntry {
  id: string;
  word: string;
  latin: string;
  aliases: string[];
  level: CurseLevel;
  type: CurseType;
  meaning: { en: string; ru?: string };
  usage: Bilingual;
  example?: Bilingual;
  source?: string;
  imported?: boolean;
}

// Original glosses and examples; see curse-SOURCE.md for editorial scope.
export const curatedCurseWords: CurseEntry[] = ([
  {
    id: "idinakhuy",
    word: "иди́ на́ хуй",
    latin: "idi na khuy",
    aliases: ["иди нахуй", "idi nakhuy", "idi nahuy", "idi nahui", "idi na hui", "idite nakhuy", "идите на хуй"],
    level: "obscene",
    type: "exclamation",
    meaning: { en: "Fuck off; go fuck yourself", ru: "Крайне грубое требование уйти или отстать" },
    usage: {
      en:
        "A direct, strongly obscene dismissal addressed to another person. Идите на хуй addresses several people or uses the вы form.",
      ru:
        "Прямое матерное требование уйти или отстать. «Идите на хуй» обращено к нескольким людям или к собеседнику на «вы».",
    },
    example: { ru: "Он разозлился и сказал: «Иди на хуй!»", en: "He got angry and said, ‘Fuck off!’" },
    source: "https://en.wiktionary.org/wiki/иди_на_хуй#Russian",
  },
  {
    id: "blin",
    word: "блин",
    latin: "blin",
    aliases: [],
    level: "mild",
    type: "exclamation",
    meaning: { en: "Damn; darn", ru: "Досада или удивление" },
    usage: {
      en: "Literally a pancake. A soft substitute for a stronger swear word; informal, not neutral.",
      ru: "Буквально — блин. Мягкая замена матерного восклицания; разговорное, не нейтральное слово.",
    },
    example: { ru: "Блин, я забыл ключи!", en: "Damn, I forgot my keys!" },
  },
  {
    id: "chert",
    word: "чёрт",
    latin: "chyort",
    aliases: [],
    level: "mild",
    type: "exclamation",
    meaning: { en: "Damn; devil", ru: "Досада; буквально — нечистый дух" },
    usage: {
      en: "An everyday expression of annoyance. Also appears in чёрт возьми, roughly ‘damn it’.",
      ru: "Восклицание при досаде. Встречается и в выражении «чёрт возьми».",
    },
    example: { ru: "Чёрт, автобус уже ушёл.", en: "Damn, the bus has already left." },
  },
  {
    id: "yolki",
    word: "ёлки-па́лки",
    latin: "yolki-palki",
    aliases: [],
    level: "mild",
    type: "exclamation",
    meaning: { en: "Oh, darn; good grief", ru: "Досада или удивление без мата" },
    usage: {
      en: "A playful euphemistic exclamation. Literally ‘fir trees and sticks’.",
      ru: "Шутливое восклицание, заменяющее более грубую брань.",
    },
    example: { ru: "Ёлки-палки, опять дождь!", en: "Oh, darn, rain again!" },
  },
  {
    id: "kapets",
    word: "капе́ц",
    latin: "kapets",
    aliases: [],
    level: "mild",
    type: "exclamation",
    meaning: { en: "We’re done for; what a disaster", ru: "Конец; провал; сильное удивление" },
    usage: {
      en: "An informal euphemism for пиздец. Can describe a setback or express disbelief.",
      ru: "Разговорная замена слова «пиздец». Обозначает неудачу или выражает изумление.",
    },
    example: { ru: "Капец, файл не сохранился.", en: "What a disaster, the file didn’t save." },
  },
  {
    id: "fig",
    word: "фиг",
    latin: "fig",
    aliases: [],
    level: "mild",
    type: "expression",
    meaning: { en: "A softened swear word in fixed phrases", ru: "Мягкая замена грубого слова в оборотах" },
    usage: {
      en: "Meaning depends on the phrase: фиг знает means ‘who knows’; ни фига can mean ‘nothing at all’.",
      ru: "Значение зависит от оборота: «фиг знает» — неизвестно; «ни фига» — совсем ничего.",
    },
    example: { ru: "Фиг знает, где мой зонт.", en: "Who knows where my umbrella is." },
  },
  {
    id: "fignya",
    word: "фигня́",
    latin: "fignya",
    aliases: [],
    level: "mild",
    type: "expression",
    meaning: { en: "Nonsense; rubbish; something trivial", ru: "Ерунда; что-то неважное или плохое" },
    usage: {
      en: "A dismissive informal word. Can belittle someone’s work or concern.",
      ru: "Пренебрежительное разговорное слово. Может обесценивать чужую работу или переживания.",
    },
    example: { ru: "Это фигня, скоро починим.", en: "It’s nothing serious; we’ll fix it soon." },
  },
  {
    id: "durak",
    word: "дура́к",
    latin: "durak",
    aliases: ["дура"],
    level: "rude",
    type: "insult",
    meaning: { en: "Fool; idiot", ru: "Оскорбительное обозначение глупого человека" },
    usage: {
      en: "A personal insult, not mat. The feminine form is дура.",
      ru: "Личное оскорбление, не мат. Форма женского рода — «дура».",
    },
    example: { ru: "Не будь дураком, возьми зонт.", en: "Don’t be a fool; take an umbrella." },
  },
  {
    id: "svoloch",
    word: "сво́лочь",
    latin: "svoloch",
    aliases: [],
    level: "rude",
    type: "insult",
    meaning: { en: "Bastard; scumbag", ru: "Подлый, неприятный человек" },
    usage: {
      en: "A hostile personal insult that can refer to any gender.",
      ru: "Враждебное оскорбление человека любого пола.",
    },
    example: { ru: "Какая сволочь украла велосипед?", en: "What bastard stole the bicycle?" },
  },
  {
    id: "suka",
    word: "су́ка",
    latin: "suka",
    aliases: ["cyka"],
    level: "rude",
    type: "insult",
    meaning: { en: "Bitch; bastard; also an angry exclamation", ru: "Грубое оскорбление или восклицание" },
    usage: {
      en: "Literally a female dog. As an insult it can target any gender; its force depends heavily on tone.",
      ru: "Буквально — самка собаки. Как оскорбление относится к людям любого пола; сила зависит от интонации.",
    },
    example: { ru: "Сука, опять всё сломалось!", en: "Shit, everything broke again!" },
  },
  {
    id: "zhopa",
    word: "жо́па",
    latin: "zhopa",
    aliases: [],
    level: "rude",
    type: "expression",
    meaning: { en: "Ass; a terrible situation", ru: "Ягодицы; тяжёлое положение" },
    usage: {
      en: "Vulgar. В жопе means ‘in deep trouble’ as well as having a literal meaning.",
      ru: "Вульгарное слово. «В жопе» переносно означает «в очень плохом положении».",
    },
    example: { ru: "С ремонтом полная жопа.", en: "The renovation is a total mess." },
  },
  {
    id: "govno",
    word: "говно́",
    latin: "govno",
    aliases: [],
    level: "rude",
    type: "expression",
    meaning: { en: "Shit; something worthless", ru: "Экскременты; что-то очень плохое" },
    usage: {
      en: "A vulgar dismissal of quality as well as a literal word for excrement.",
      ru: "Грубая оценка качества, а также буквальное обозначение экскрементов.",
    },
    example: { ru: "Этот клей — говно, ничего не держит.", en: "This glue is shit; it won’t hold anything." },
  },
  {
    id: "khren",
    word: "хрен",
    latin: "khren",
    aliases: [],
    level: "rude",
    type: "expression",
    meaning: { en: "Hell; a euphemistic swear word", ru: "Грубоватая замена матерного слова" },
    usage: {
      en: "Literally horseradish. In какого хрена? it means roughly ‘what the hell?’.",
      ru: "Буквально — растение. «Какого хрена?» — грубый вопрос о причине или цели.",
    },
    example: { ru: "Какого хрена свет не работает?", en: "Why the hell aren’t the lights working?" },
  },
  {
    id: "blyad",
    word: "блядь",
    latin: "blyad",
    aliases: ["блять", "бля", "blyat"],
    level: "obscene",
    type: "exclamation",
    meaning: {
      en: "Fuck; an obscene exclamation or sexual insult",
      ru: "Матерное восклицание; также сексуальное оскорбление",
    },
    usage: {
      en:
        "Often expresses frustration without a literal sexual meaning. The noun is a degrading insult, roughly ‘whore’. Блять is a common informal spelling.",
      ru:
        "Часто выражает досаду без буквального сексуального смысла. Как существительное — унизительное оскорбление. «Блять» — распространённое неформальное написание.",
    },
    example: { ru: "Блядь, я опоздал на поезд!", en: "Fuck, I missed the train!" },
  },
  {
    id: "khuy",
    word: "хуй",
    latin: "khuy",
    aliases: ["hui"],
    level: "obscene",
    type: "expression",
    meaning: { en: "Dick; cock", ru: "Матерное название пениса" },
    usage: {
      en: "A core mat word with many nonliteral phrases. Хуй знает is an obscene ‘who the fuck knows’.",
      ru: "Один из основных корней мата. Во многих оборотах смысл переносный: «хуй знает» — неизвестно.",
    },
    example: { ru: "Хуй знает, куда делся чек.", en: "Who the fuck knows where the receipt went." },
  },
  {
    id: "pizda",
    word: "пизда́",
    latin: "pizda",
    aliases: [],
    level: "obscene",
    type: "expression",
    meaning: { en: "Cunt; being completely done for", ru: "Матерное название женских половых органов; конец, гибель" },
    usage: {
      en: "An obscene anatomical term. In чему-то пизда it means something is ruined or finished.",
      ru: "Нецензурное анатомическое слово. В обороте «чему-то пизда» означает полный крах или поломку.",
    },
    example: { ru: "Похоже, мотору пизда.", en: "Looks like the engine is fucked." },
  },
  {
    id: "ebat",
    word: "еба́ть",
    latin: "yebat",
    aliases: [],
    level: "obscene",
    type: "verb",
    meaning: { en: "To fuck; also an exclamation of shock", ru: "Совершать половой акт; также восклицание" },
    usage: {
      en: "A core mat verb. Used alone as an exclamation, it can express surprise without referring to sex.",
      ru: "Один из основных матерных глаголов. Как восклицание может выражать удивление без связи с сексом.",
    },
    example: { ru: "Ебать, какой огромный экран!", en: "Fuck, what a huge screen!" },
  },
  {
    id: "pizdets",
    word: "пизде́ц",
    latin: "pizdets",
    aliases: [],
    level: "obscene",
    type: "exclamation",
    meaning: { en: "A total disaster; holy fuck", ru: "Полный крах; крайнее удивление" },
    usage: {
      en: "Usually marks a disastrous situation, but can also react to something overwhelming or astonishing.",
      ru: "Чаще обозначает катастрофическую ситуацию, но может выражать потрясение или изумление.",
    },
    example: { ru: "Пиздец, все билеты проданы.", en: "Fuck, all the tickets are sold out." },
  },
  {
    id: "khuynya",
    word: "хуйня́",
    latin: "khuynya",
    aliases: [],
    level: "obscene",
    type: "expression",
    meaning: { en: "Bullshit; crap; some worthless thing", ru: "Чушь; ерунда; что-то плохое или непонятное" },
    usage: {
      en: "A strongly dismissive word for an idea, object, or situation; not necessarily an accusation of lying.",
      ru: "Резко пренебрежительное слово о мысли, предмете или ситуации; не обязательно обвинение во лжи.",
    },
    example: { ru: "Инструкция — полная хуйня.", en: "The instructions are total bullshit." },
  },
  {
    id: "okhuet",
    word: "охуе́ть",
    latin: "okhuet",
    aliases: [],
    level: "obscene",
    type: "verb",
    meaning: { en: "To be fucking stunned; to go too far", ru: "Сильно удивиться; обнаглеть" },
    usage: {
      en: "Can express amazement or anger at unreasonable behavior. The interpretation depends on context.",
      ru: "Передаёт изумление либо возмущение чьей-то наглостью. Смысл определяется контекстом.",
    },
    example: { ru: "Охуеть, сколько снега!", en: "Holy fuck, look at all that snow!" },
  },
  {
    id: "zaebis",
    word: "заеби́сь",
    latin: "zayebis",
    aliases: [],
    level: "obscene",
    type: "exclamation",
    meaning: { en: "Fucking great", ru: "Очень хорошо, отлично" },
    usage: {
      en: "An obscene expression of approval. Can be sarcastic when something has gone wrong.",
      ru: "Матерная положительная оценка. При неудаче может употребляться саркастически.",
    },
    example: { ru: "Заебись, всё заработало!", en: "Fucking great, it all works now!" },
  },
  {
    id: "zaebat",
    word: "заеба́ть",
    latin: "zayebat",
    aliases: ["заебал", "заебала", "заебало", "заебали"],
    level: "obscene",
    type: "verb",
    meaning: { en: "To annoy or exhaust completely", ru: "Крайне надоесть или утомить" },
    usage: {
      en: "Typically appears as заебал / заебала / заебало / заебали when saying something has become unbearable.",
      ru: "Формы «заебал», «заебала», «заебало», «заебали» выражают крайнюю усталость или раздражение.",
    },
    example: { ru: "Заебал этот шум за окном.", en: "I’m fucking sick of that noise outside." },
  },
  {
    id: "pokhuy",
    word: "по́хуй",
    latin: "pokhuy",
    aliases: ["по хуй"],
    level: "obscene",
    type: "expression",
    meaning: { en: "Don’t give a fuck", ru: "Совершенно безразлично" },
    usage: {
      en: "Usually with a dative pronoun: мне похуй. Conveys blunt indifference and can sound dismissive.",
      ru: "Обычно с дательным падежом: «мне похуй». Резко выражает безразличие.",
    },
    example: { ru: "Мне похуй, какого цвета чехол.", en: "I don’t give a fuck what color the case is." },
  },
  {
    id: "poshel",
    word: "пошёл на хуй",
    latin: "poshyol na khuy",
    aliases: ["пошёл нахуй", "пошла на хуй", "пошли на хуй"],
    level: "obscene",
    type: "insult",
    meaning: { en: "Fuck off", ru: "Крайне грубое требование уйти" },
    usage: {
      en: "A directly hostile dismissal. Forms change with the addressee: пошла, пошли.",
      ru: "Прямое враждебное оскорбление. Форма зависит от адресата: «пошла», «пошли».",
    },
    example: { ru: "Он крикнул: «Пошёл на хуй!»", en: "He shouted, ‘Fuck off!’" },
  },
  {
    id: "mudak",
    word: "муда́к",
    latin: "mudak",
    aliases: [],
    level: "obscene",
    type: "insult",
    meaning: { en: "Asshole; prick", ru: "Грубое оскорбление неприятного или глупого человека" },
    usage: {
      en: "A strong personal insult, usually aimed at a man. Register labels vary between dictionaries.",
      ru: "Сильное личное оскорбление, обычно в адрес мужчины. Словарные пометы могут различаться.",
    },
    example: { ru: "Какой-то мудак перегородил выезд.", en: "Some asshole blocked the exit." },
  },
  {
    id: "ofiget",
    word: "офиге́ть",
    latin: "ofiget",
    aliases: ["офигел", "офигела"],
    level: "mild",
    type: "verb",
    meaning: { en: "To be stunned; to act as if you’ve lost your mind", ru: "Поразиться; начать вести себя неразумно" },
    usage: {
      en: "A softened alternative to охуеть. As an exclamation it can express amazement or disbelief.",
      ru: "Смягчённая замена слова «охуеть». Как восклицание передаёт изумление или недоверие.",
    },
    example: { ru: "Офигеть, какой вид с крыши!", en: "Wow, what a view from the roof!" },
    source: "https://ru.wiktionary.org/wiki/офигеть",
  },
  {
    id: "ofigenny",
    word: "офиге́нный",
    latin: "ofigenny",
    aliases: ["офигенная", "офигенное", "офигенно"],
    level: "mild",
    type: "expression",
    meaning: { en: "Awesome; incredibly good", ru: "Потрясающий, очень хороший" },
    usage: {
      en: "Informal praise with a euphemistic swear-word root. Офигенно is the related adverb.",
      ru: "Разговорная похвала с эвфемистическим корнем. Родственное наречие — «офигенно».",
    },
    example: { ru: "У них офигенный завтрак.", en: "Their breakfast is awesome." },
    source: "https://ru.wiktionary.org/wiki/офигенный",
  },
  {
    id: "pofig",
    word: "по́фиг",
    latin: "pofig",
    aliases: ["пофигу", "по фигу"],
    level: "mild",
    type: "expression",
    meaning: { en: "Don’t care; couldn’t care less", ru: "Безразлично, всё равно" },
    usage: {
      en: "Often used with мне. Softer than похуй, but it can still dismiss someone’s concerns.",
      ru: "Часто употребляется с «мне». Мягче слова «похуй», но может выражать пренебрежение к чужим переживаниям.",
    },
    example: { ru: "Мне пофиг, где сидеть.", en: "I don’t care where I sit." },
    source: "https://ru.wiktionary.org/wiki/пофиг",
  },
  {
    id: "nifiga",
    word: "ни фига́",
    latin: "ni figa",
    aliases: ["нифига"],
    level: "mild",
    type: "expression",
    meaning: { en: "Nothing at all; not a bit", ru: "Совсем ничего; нисколько" },
    usage: {
      en: "Emphasizes a negative statement. The longer ни фига себе! is an exclamation of surprise.",
      ru: "Усиливает отрицание. Более длинное «ни фига себе!» выражает удивление.",
    },
    example: { ru: "В темноте ни фига не видно.", en: "You can’t see a damn thing in the dark." },
    source: "https://ru.wiktionary.org/wiki/ни_фига",
  },
  {
    id: "nafig",
    word: "на фиг",
    latin: "na fig",
    aliases: ["нафиг"],
    level: "mild",
    type: "expression",
    meaning: { en: "Away; to hell with it", ru: "Прочь; долой" },
    usage: {
      en: "A softened dismissal, as in иди на фиг. Still rude when directed at someone.",
      ru: "Смягчённая форма отсылки: «иди на фиг». При обращении к человеку всё равно звучит грубо.",
    },
    example: { ru: "Выброси на фиг этот сломанный будильник.", en: "Just chuck that broken alarm clock out." },
    source: "https://ru.wiktionary.org/wiki/на_фиг",
  },
  {
    id: "yomoyo",
    word: "ё-моё",
    latin: "yo-moyo",
    aliases: ["ё моё"],
    level: "mild",
    type: "exclamation",
    meaning: { en: "Oh, man; for goodness’ sake", ru: "Досада, разочарование или изумление" },
    usage: {
      en: "A euphemistic exclamation whose mood can range from frustration to delight.",
      ru: "Эвфемистическое восклицание: от раздражения до восторга, в зависимости от интонации.",
    },
    example: { ru: "Ё-моё, я перепутал этаж!", en: "Oh, man, I got the wrong floor!" },
    source: "https://ru.wiktionary.org/wiki/ё-моё",
  },
  {
    id: "chertvozmi",
    word: "чёрт возьми́",
    latin: "chyort vozmi",
    aliases: [],
    level: "mild",
    type: "exclamation",
    meaning: { en: "Damn it; damn", ru: "Возглас досады или недовольства" },
    usage: {
      en: "A fixed exclamation. Usually expresses irritation rather than a literal wish involving a devil.",
      ru: "Устойчивое восклицание. Обычно передаёт раздражение, а не буквальное пожелание.",
    },
    example: { ru: "Чёрт возьми, принтер опять зажевал бумагу!", en: "Damn it, the printer jammed again!" },
    source: "https://ru.wiktionary.org/wiki/чёрт_возьми",
  },
  {
    id: "khreny",
    word: "хрень",
    latin: "khren’",
    aliases: [],
    level: "rude",
    type: "expression",
    meaning: { en: "Crap; nonsense; some unwanted thing", ru: "Ерунда; ненужная или плохая вещь" },
    usage: {
      en: "A dismissive placeholder for something you dislike or cannot name. It is softer than хуйня.",
      ru: "Пренебрежительное обозначение неприятного или неизвестного предмета. Мягче слова «хуйня».",
    },
    example: { ru: "Что за хрень лежит в коробке?", en: "What is this crap in the box?" },
    source: "https://ru.wiktionary.org/wiki/хрень",
  },
  {
    id: "khrenovy",
    word: "хрено́вый",
    latin: "khrenovy",
    aliases: ["хреновая", "хреновое", "хреново"],
    level: "rude",
    type: "expression",
    meaning: { en: "Lousy; crappy", ru: "Плохой, неудачный" },
    usage: {
      en: "A coarse assessment of quality. The related хреново can also describe feeling unwell.",
      ru: "Грубоватая оценка качества. Родственное «хреново» также описывает плохое самочувствие.",
    },
    example: { ru: "Это был хреновый план.", en: "That was a lousy plan." },
    source: "https://ru.wiktionary.org/wiki/хреновый",
  },
  {
    id: "okhrenet",
    word: "охрене́ть",
    latin: "okhrenet",
    aliases: ["охренел", "охренела"],
    level: "rude",
    type: "verb",
    meaning: { en: "To be stunned; to act outrageously", ru: "Поразиться; потерять чувство меры" },
    usage: {
      en: "A coarse euphemism for охуеть. Ты охренел? can challenge someone’s unreasonable behavior.",
      ru: "Грубоватый эвфемизм к «охуеть». «Ты охренел?» может выражать возмущение чужим поведением.",
    },
    example: { ru: "Охренеть, сколько стоит доставка!", en: "Bloody hell, look at the delivery charge!" },
    source: "https://ru.wiktionary.org/wiki/охренеть",
  },
  {
    id: "zadolbat",
    word: "задолба́ть",
    latin: "zadolbat",
    aliases: ["задолбал", "задолбала", "задолбало", "задолбали"],
    level: "rude",
    type: "verb",
    meaning: {
      en: "To get on someone’s nerves; to wear someone out",
      ru: "Надоесть или утомить повторяющимися действиями",
    },
    usage: {
      en: "Describes repeated irritation. A coarser alternative to надоесть, without the mat root of заебать.",
      ru: "О повторяющемся раздражении. Грубее нейтрального «надоесть», но без матерного корня слова «заебать».",
    },
    example: { ru: "Задолбали эти звонки с рекламой.", en: "I’m sick of these advertising calls." },
    source: "https://ru.wiktionary.org/wiki/задолбать",
  },
  {
    id: "zasranets",
    word: "засра́нец",
    latin: "zasranets",
    aliases: ["засранка"],
    level: "rude",
    type: "insult",
    meaning: { en: "Little shit; dirty bastard", ru: "Пакостный, неприятный человек" },
    usage: {
      en: "A coarse insult for someone behaving badly. Засранка is the feminine form.",
      ru: "Грубое оскорбление человека за неприятные поступки. Женская форма — «засранка».",
    },
    example: { ru: "Этот засранец испортил мне куртку.", en: "That little shit ruined my jacket." },
    source: "https://ru.wiktionary.org/wiki/засранец",
  },
  {
    id: "gad",
    word: "гад",
    latin: "gad",
    aliases: [],
    level: "rude",
    type: "insult",
    meaning: { en: "Bastard; creep", ru: "Подлый или отвратительный человек" },
    usage: {
      en: "An insult expressing disgust at someone’s conduct; the word also has non-insulting animal meanings.",
      ru: "Выражает отвращение к чьему-то поведению. У слова есть и небранные значения, связанные с животными.",
    },
    example: { ru: "Какой гад выкинул мои письма?", en: "What bastard threw away my letters?" },
    source: "https://ru.wiktionary.org/wiki/гад",
  },
  {
    id: "dryan",
    word: "дрянь",
    latin: "dryan",
    aliases: [],
    level: "rude",
    type: "insult",
    meaning: { en: "Scum; a nasty person; rubbish", ru: "Низкий человек; плохая, негодная вещь" },
    usage: {
      en: "Applied to a person, it is contemptuous. Applied to an object, it dismisses its quality.",
      ru: "О человеке — презрительное оскорбление; о предмете — отрицательная оценка качества.",
    },
    example: { ru: "Он назвал обманщика дрянью.", en: "He called the fraudster scum." },
    source: "https://ru.wiktionary.org/wiki/дрянь",
  },
  {
    id: "merzavets",
    word: "мерза́вец",
    latin: "merzavets",
    aliases: ["мерзавка"],
    level: "rude",
    type: "insult",
    meaning: { en: "Scoundrel; bastard", ru: "Негодяй, отвратительный человек" },
    usage: {
      en: "Condemns someone’s character or actions. An insult, but not mat.",
      ru: "Осуждает характер или поступки человека. Бранное слово, но не мат.",
    },
    example: { ru: "Мерзавец забрал деньги и исчез.", en: "The scoundrel took the money and disappeared." },
    source: "https://ru.wiktionary.org/wiki/мерзавец",
  },
  {
    id: "kozel",
    word: "козёл",
    latin: "kozyol",
    aliases: ["козлы"],
    level: "rude",
    type: "insult",
    meaning: { en: "Jerk; asshole", ru: "Неприятный или подлый человек" },
    usage: {
      en: "Literally a male goat. As a personal insult, it usually targets a man.",
      ru: "Буквально — самец козы. Как личное оскорбление обычно относится к мужчине.",
    },
    example: { ru: "Этот козёл занял два парковочных места.", en: "That jerk took up two parking spaces." },
    source: "https://ru.wiktionary.org/wiki/козёл",
  },
  {
    id: "pipets",
    word: "пипе́ц",
    latin: "pipets",
    aliases: ["ппц"],
    level: "rude",
    type: "exclamation",
    meaning: { en: "What a disaster; we’re screwed", ru: "Крах; сильное удивление или досада" },
    usage: {
      en: "A euphemism for пиздец. The abbreviation ппц is common in informal messages.",
      ru: "Эвфемизм к «пиздец». Сокращение «ппц» встречается в неформальной переписке.",
    },
    example: { ru: "Пипец, до утра нет электричества.", en: "We’re screwed, there’s no electricity until morning." },
    source: "https://ru.wiktionary.org/wiki/пипец",
  },
  {
    id: "dolboyob",
    word: "долбоёб",
    latin: "dolboyob",
    aliases: ["долбоёбы"],
    level: "obscene",
    type: "insult",
    meaning: { en: "Fuckwit; fucking idiot", ru: "Крайне грубое оскорбление за глупость" },
    usage: {
      en: "A strong personal insult aimed at someone considered foolish or incompetent.",
      ru: "Сильное личное оскорбление человека, которого считают глупым или бестолковым.",
    },
    example: { ru: "Какой долбоёб заклеил вентиляцию?", en: "What fuckwit taped over the ventilation?" },
    source: "https://ru.wiktionary.org/wiki/долбоёб",
  },
  {
    id: "uyobok",
    word: "уёбок",
    latin: "uyobok",
    aliases: ["уёбки"],
    level: "obscene",
    type: "insult",
    meaning: { en: "Fucker; loathsome asshole", ru: "Крайне грубое обозначение неприятного человека" },
    usage: {
      en: "An intensely hostile insult, often expressing disgust at someone’s behavior.",
      ru: "Резко враждебное оскорбление, часто выражающее отвращение к поведению человека.",
    },
    example: { ru: "Этот уёбок разбил чужое окно и убежал.", en: "That fucker broke someone’s window and ran away." },
    source: "https://ru.wiktionary.org/wiki/уёбок",
  },
  {
    id: "yobany",
    word: "ёбаный",
    latin: "yobany",
    aliases: ["ёбаная", "ёбаное", "ёбаные"],
    level: "obscene",
    type: "expression",
    meaning: { en: "Fucking; goddamn", ru: "Матерное определение, усиливающее раздражение" },
    usage: {
      en: "Often modifies a noun to vent anger. In this use it does not describe a sexual act.",
      ru: "Часто ставится перед существительным для выражения злости. В таком употреблении не описывает половой акт.",
    },
    example: { ru: "Ёбаный замок опять заклинило.", en: "The fucking lock jammed again." },
    source: "https://ru.wiktionary.org/wiki/ёбаный",
  },
  {
    id: "yebanuty",
    word: "ебану́тый",
    latin: "yebanuty",
    aliases: ["ебанутая", "ебанутое", "ебанутые"],
    level: "obscene",
    type: "insult",
    meaning: { en: "Fucking nuts; out of one’s mind", ru: "Матерная оценка чьей-то неразумности" },
    usage: {
      en: "A derogatory judgment of a person or idea, not a medical description.",
      ru: "Уничижительная оценка человека или идеи, а не медицинское описание.",
    },
    example: { ru: "Он предложил какой-то ебанутый план.", en: "He suggested some fucking insane plan." },
    source: "https://ru.wiktionary.org/wiki/ебанутый",
  },
  {
    id: "okhuyenny",
    word: "охуе́нный",
    latin: "okhuyenny",
    aliases: ["охуенная", "охуенное", "охуенно"],
    level: "obscene",
    type: "expression",
    meaning: { en: "Fucking amazing; awesome", ru: "Потрясающий, чрезвычайно хороший" },
    usage: {
      en: "Usually enthusiastic praise, despite its obscene root. It can also be used sarcastically.",
      ru: "Обычно восторженная похвала, несмотря на матерный корень. Возможен и сарказм.",
    },
    example: { ru: "У них охуенный звук на концертах.", en: "Their concert sound is fucking amazing." },
    source: "https://ru.wiktionary.org/wiki/охуенный",
  },
  {
    id: "khuyovy",
    word: "хуёвый",
    latin: "khuyovy",
    aliases: ["хуёвая", "хуёвое", "хуёво"],
    level: "obscene",
    type: "expression",
    meaning: { en: "Shitty; fucking awful", ru: "Очень плохой, скверный" },
    usage: {
      en: "An obscene negative assessment. The related хуёво also describes feeling terrible.",
      ru: "Матерная отрицательная оценка. Родственное «хуёво» также описывает плохое самочувствие.",
    },
    example: { ru: "Сегодня был хуёвый день.", en: "Today was a shitty day." },
    source: "https://ru.wiktionary.org/wiki/хуёвый",
  },
  {
    id: "dokhuya",
    word: "дохуя́",
    latin: "dokhuya",
    aliases: ["до хуя"],
    level: "obscene",
    type: "expression",
    meaning: { en: "A shitload; way too much", ru: "Очень много; слишком много" },
    usage: {
      en: "Emphasizes quantity. Whether it means an impressive amount or an excessive amount depends on context.",
      ru: "Усиливает количество. В зависимости от контекста означает просто большое или чрезмерное количество.",
    },
    example: { ru: "В очереди дохуя народу.", en: "There’s a shitload of people in the queue." },
    source: "https://ru.wiktionary.org/wiki/дохуя",
  },
  {
    id: "nikhuya",
    word: "ни хуя́",
    latin: "ni khuya",
    aliases: ["нихуя"],
    level: "obscene",
    type: "expression",
    meaning: { en: "Fuck all; not a damn thing", ru: "Совсем ничего; нисколько" },
    usage: {
      en: "Usually strengthens a negative statement. Ни хуя себе! is a separate exclamation of surprise.",
      ru: "Обычно усиливает отрицание. «Ни хуя себе!» — отдельное восклицание удивления.",
    },
    example: { ru: "Я ни хуя не слышу из-за музыки.", en: "I can’t hear a fucking thing over the music." },
    source: "https://ru.wiktionary.org/wiki/ни_хуя",
  },
  {
    id: "nakhuya",
    word: "нахуя́",
    latin: "nakhuya",
    aliases: ["на хуя"],
    level: "obscene",
    type: "expression",
    meaning: { en: "Why the fuck; what the fuck for", ru: "Зачем; для чего — в матерной форме" },
    usage: {
      en: "An aggressive or incredulous question about purpose. Often challenges the need for something.",
      ru: "Агрессивный или недоумённый вопрос о цели. Часто оспаривает необходимость действия.",
    },
    example: { ru: "Нахуя мы купили второй чайник?", en: "Why the fuck did we buy a second kettle?" },
    source: "https://ru.wiktionary.org/wiki/нахуя",
  },
  {
    id: "nakhuy",
    word: "на́хуй",
    latin: "nakhuy",
    aliases: [],
    level: "obscene",
    type: "expression",
    meaning: { en: "Why the fuck; what the fuck for", ru: "Зачем; к чему" },
    usage: {
      en: "In нахуй это нужно? it questions usefulness. Compare the dismissal пошёл на хуй, listed separately.",
      ru: "В вопросе «нахуй это нужно?» оспаривает полезность. Отсылка «пошёл на хуй» приведена отдельно.",
    },
    example: { ru: "Нахуй мне сломанный телефон?", en: "What the fuck do I need a broken phone for?" },
    source: "https://ru.wiktionary.org/wiki/нахуй",
  },
  {
    id: "pizdet",
    word: "пизде́ть",
    latin: "pizdet",
    aliases: ["пиздишь", "пиздел"],
    level: "obscene",
    type: "verb",
    meaning: { en: "To bullshit; to lie; to chatter", ru: "Врать; болтать, в том числе попусту" },
    usage: {
      en: "Can mean either idle talk or lying. Distinguish пизде́ть from пи́здить, which means to steal or beat.",
      ru: "Может обозначать как болтовню, так и ложь. Не путайте «пизде́ть» с «пи́здить» — красть или бить.",
    },
    example: { ru: "Хватит пиздеть, покажи квитанцию.", en: "Stop bullshitting and show the receipt." },
    source: "https://ru.wiktionary.org/wiki/пиздеть",
  },
  {
    id: "pizdit",
    word: "пи́здить",
    latin: "pizdit",
    aliases: ["пиздил", "пиздили"],
    level: "obscene",
    type: "verb",
    meaning: { en: "To steal; to beat someone up", ru: "Красть; избивать" },
    usage: {
      en: "The object and situation determine the sense. Stress is on the first syllable, unlike пизде́ть.",
      ru: "Значение зависит от дополнения и ситуации. Ударение на первом слоге, в отличие от «пизде́ть».",
    },
    example: {
      ru: "Кто-то повадился пиздить лампочки в подъезде.",
      en: "Someone keeps fucking stealing the light bulbs in the stairwell.",
    },
    source: "https://ru.wiktionary.org/wiki/пиздить",
  },
  {
    id: "spizdit",
    word: "спи́здить",
    latin: "spizdit",
    aliases: ["спиздил", "спиздила", "спиздили"],
    level: "obscene",
    type: "verb",
    meaning: { en: "To nick; to fucking steal", ru: "Украсть, своровать" },
    usage: {
      en: "A completed act of theft. Distinguish it from спиздеть, meaning to tell a lie.",
      ru: "Завершённое действие кражи. Отличается от «спиздеть» — соврать.",
    },
    example: { ru: "У меня спиздили насос из гаража.", en: "Someone fucking nicked my pump from the garage." },
    source: "https://ru.wiktionary.org/wiki/спиздить",
  },
  {
    id: "pizdyozh",
    word: "пиздёж",
    latin: "pizdyozh",
    aliases: [],
    level: "obscene",
    type: "expression",
    meaning: { en: "Bullshit; lies; idle chatter", ru: "Враньё; пустая болтовня" },
    usage: {
      en: "Often rejects a claim as false, though it can also refer to pointless talk.",
      ru: "Часто отрицает правдивость утверждения, но может обозначать и пустой разговор.",
    },
    example: { ru: "Про бесплатный ремонт — полный пиздёж.", en: "That claim about free repairs is total bullshit." },
    source: "https://ru.wiktionary.org/wiki/пиздёж",
  },
  {
    id: "pizdobol",
    word: "пиздобо́л",
    latin: "pizdobol",
    aliases: ["пиздабол"],
    level: "obscene",
    type: "insult",
    meaning: { en: "Bullshitter; liar; windbag", ru: "Лжец или пустомеля" },
    usage: {
      en: "Insults someone for lying or talking without substance. Пиздабол is an informal phonetic spelling.",
      ru: "Оскорбляет за ложь или пустые разговоры. «Пиздабол» — неформальное написание по произношению.",
    },
    example: { ru: "Этот пиздобол обещал закончить вчера.", en: "That bullshitter promised to finish yesterday." },
    source: "https://ru.wiktionary.org/wiki/пиздобол",
  },
  {
    id: "nayebat",
    word: "наеба́ть",
    latin: "nayebat",
    aliases: ["наебал", "наебала", "наебали"],
    level: "obscene",
    type: "verb",
    meaning: { en: "To rip off; to screw someone over", ru: "Обмануть, надуть" },
    usage: {
      en: "Often describes a scam or dishonest deal. The person deceived is the direct object.",
      ru: "Часто о мошенничестве или нечестной сделке. Обманутый человек обозначается прямым дополнением.",
    },
    example: { ru: "Меня наебали со сдачей.", en: "They screwed me over on the change." },
    source: "https://ru.wiktionary.org/wiki/наебать",
  },
  {
    id: "proyebat",
    word: "проеба́ть",
    latin: "proyebat",
    aliases: ["проебал", "проебала", "проебали"],
    level: "obscene",
    type: "verb",
    meaning: {
      en: "To lose carelessly; to waste; to miss",
      ru: "Потерять по невнимательности; упустить; потратить впустую",
    },
    usage: {
      en: "Often implies that carelessness caused the loss of an object, opportunity, or time.",
      ru: "Часто подразумевает небрежность при потере вещи, возможности или времени.",
    },
    example: { ru: "Я проебал последний автобус.", en: "I fucking missed the last bus." },
    source: "https://ru.wiktionary.org/wiki/проебать",
  },
  {
    id: "otyebatsya",
    word: "отъеба́ться",
    latin: "otyebatsya",
    aliases: ["отъебись", "отъебитесь", "отъебался"],
    level: "obscene",
    type: "verb",
    meaning: { en: "To leave someone the fuck alone; to stop pestering", ru: "Отстать, прекратить приставать" },
    usage: {
      en: "Often heard as the hostile command отъебись. The person being bothered follows от.",
      ru: "Часто употребляется как резкая команда «отъебись». После «от» указывается тот, кому надоедают.",
    },
    example: { ru: "Отъебись от меня со своими советами.", en: "Leave me the fuck alone with your advice." },
    source: "https://ru.wiktionary.org/wiki/отъебаться",
  },
  {
    id: "yobtvoyumat",
    word: "ёб твою́ мать",
    latin: "yob tvoyu mat",
    aliases: [],
    level: "obscene",
    type: "exclamation",
    meaning: { en: "Fucking hell; for fuck’s sake", ru: "Матерный возглас злости, досады или удивления" },
    usage: {
      en: "Contains a literal sexual insult involving a mother, but often functions as a general exclamation.",
      ru: "Содержит буквальное сексуальное оскорбление с упоминанием матери, но часто служит общим восклицанием.",
    },
    example: { ru: "Ёб твою мать, вода на полу!", en: "Fucking hell, there’s water on the floor!" },
    source: "https://ru.wiktionary.org/wiki/ёб_твою_мать",
  },
  {
    id: "blyakhamukha",
    word: "бля́ха-му́ха",
    latin: "blyakha-mukha",
    aliases: ["бляха муха"],
    level: "mild",
    type: "exclamation",
    meaning: { en: "Darn it; oh, damn", ru: "Возглас досады или удивления" },
    usage: {
      en: "A rhyming substitute for stronger swearing. Often sounds playful even when expressing annoyance.",
      ru: "Рифмованная замена более грубой брани. Даже при раздражении может звучать шутливо.",
    },
    example: { ru: "Бляха-муха, я сел не в тот автобус!", en: "Darn it, I got on the wrong bus!" },
    source: "https://ru.wiktionary.org/wiki/бляха-муха",
  },
  {
    id: "yoshkinkot",
    word: "ёшкин кот",
    latin: "yoshkin kot",
    aliases: [],
    level: "mild",
    type: "exclamation",
    meaning: { en: "Good grief; for goodness’ sake", ru: "Восклицание недоумения, досады или изумления" },
    usage: {
      en: "A humorous euphemistic exclamation. The phrase is not normally about an actual cat.",
      ru: "Шутливое эвфемистическое восклицание. Обычно не связано с настоящим котом.",
    },
    example: { ru: "Ёшкин кот, куда делась зарядка?", en: "Good grief, where did the charger go?" },
    source: "https://ru.wiktionary.org/wiki/ёшкин_кот",
  },
  {
    id: "chertpoberi",
    word: "чёрт побери́",
    latin: "chyort poberi",
    aliases: [],
    level: "mild",
    type: "exclamation",
    meaning: { en: "Damn it; damn", ru: "Досада, удивление или эмоциональное одобрение" },
    usage: {
      en: "Often expresses irritation, but can also strengthen praise or satisfaction.",
      ru: "Часто выражает раздражение, но может усиливать похвалу или удовольствие.",
    },
    example: { ru: "Чёрт побери, у нас получилось!", en: "Damn, we actually did it!" },
    source: "https://ru.wiktionary.org/wiki/чёрт_побери",
  },
  {
    id: "figovy",
    word: "фиго́вый",
    latin: "figovy",
    aliases: ["фиговая", "фиговое", "фигово"],
    level: "mild",
    type: "expression",
    meaning: { en: "Lousy; no good", ru: "Плохой, некачественный" },
    usage: {
      en: "A softened negative assessment. Stress distinguishes фиго́вый ‘lousy’ from фи́говый ‘of figs’.",
      ru: "Смягчённая отрицательная оценка. Ударение отличает «фиго́вый» — плохой от «фи́говый» — связанный с инжиром.",
    },
    example: { ru: "У этого радио фиговый приём.", en: "This radio gets lousy reception." },
    source: "https://ru.wiktionary.org/wiki/фиговый",
  },
  {
    id: "dofiga",
    word: "до фига́",
    latin: "do figa",
    aliases: ["дофига"],
    level: "mild",
    type: "expression",
    meaning: { en: "Loads; a hell of a lot", ru: "Очень много" },
    usage: {
      en: "An informal quantity expression, softer than дохуя. It can convey surprise at how much there is.",
      ru: "Разговорное обозначение количества, мягче «дохуя». Может передавать удивление большим количеством.",
    },
    example: {
      ru: "В рюкзаке до фига ненужных вещей.",
      en: "There’s a hell of a lot of useless stuff in the backpack.",
    },
    source: "https://ru.wiktionary.org/wiki/до_фига",
  },
  {
    id: "nafiga",
    word: "на фига́",
    latin: "na figa",
    aliases: ["нафига"],
    level: "mild",
    type: "expression",
    meaning: { en: "What the heck for; why on earth", ru: "Зачем, для чего — с раздражением" },
    usage: {
      en: "Questions the purpose of something, often dismissively. Compare на фиг, which can mean ‘away’.",
      ru: "Часто пренебрежительно спрашивает о цели. Сравните «на фиг» в значении «прочь».",
    },
    example: { ru: "На фига мы взяли три зонта?", en: "What the heck did we bring three umbrellas for?" },
    source: "https://ru.wiktionary.org/wiki/на_фига",
  },
  {
    id: "nifigasebe",
    word: "ни фига́ себе́",
    latin: "ni figa sebe",
    aliases: ["нифига себе"],
    level: "mild",
    type: "exclamation",
    meaning: { en: "Wow; no way; holy cow", ru: "Сильное удивление" },
    usage: {
      en: "The complete phrase expresses surprise. Without себе, ни фига usually strengthens a negative statement.",
      ru: "Целое выражение передаёт удивление. Без «себе» сочетание «ни фига» обычно усиливает отрицание.",
    },
    example: { ru: "Ни фига себе, ты сам собрал этот стол?", en: "Wow, did you build this table yourself?" },
    source: "https://ru.wiktionary.org/wiki/ни_фига_себе",
  },
  {
    id: "pridurok",
    word: "приду́рок",
    latin: "pridurok",
    aliases: ["придурки"],
    level: "rude",
    type: "insult",
    meaning: { en: "Idiot; jerk; dumbass", ru: "Оскорбительное обозначение глупого человека" },
    usage: {
      en: "Insults someone’s judgment or behavior. It is not a clinical description.",
      ru: "Оскорбительная оценка чьих-то решений или поведения, а не медицинское описание.",
    },
    example: { ru: "Какой придурок оставил дверь открытой?", en: "What idiot left the door open?" },
    source: "https://ru.wiktionary.org/wiki/придурок",
  },
  {
    id: "idiot",
    word: "идио́т",
    latin: "idiot",
    aliases: ["идиотка", "идиоты"],
    level: "rude",
    type: "insult",
    meaning: { en: "Idiot; fool", ru: "Оскорбление за глупость или неразумный поступок" },
    usage: {
      en: "Here it is an everyday insult, not the historical medical term. The feminine form is идиотка.",
      ru: "Здесь — бытовое оскорбление, а не исторический медицинский термин. Женская форма — «идиотка».",
    },
    example: { ru: "Я как идиот ждал у другого входа.", en: "I waited at the other entrance like an idiot." },
    source: "https://ru.wiktionary.org/wiki/идиот",
  },
  {
    id: "tupitsa",
    word: "тупи́ца",
    latin: "tupitsa",
    aliases: [],
    level: "rude",
    type: "insult",
    meaning: { en: "Dunce; dimwit", ru: "Оскорбительное название несообразительного человека" },
    usage: {
      en: "A belittling word for someone considered slow to understand. It can refer to any gender.",
      ru:
        "Уничижительное слово о человеке, который, по мнению говорящего, плохо соображает. Относится к людям любого пола.",
    },
    example: { ru: "Он назвал меня тупицей из-за одной ошибки.", en: "He called me a dimwit over one mistake." },
    source: "https://ru.wiktionary.org/wiki/тупица",
  },
  {
    id: "bolvan",
    word: "болва́н",
    latin: "bolvan",
    aliases: ["болваны"],
    level: "rude",
    type: "insult",
    meaning: { en: "Blockhead; fool", ru: "Бестолковый человек" },
    usage: {
      en: "Usually aimed at a man for a foolish action. The word also has unrelated technical meanings.",
      ru: "Обычно о мужчине, совершившем глупость. У слова есть и отдельные технические значения.",
    },
    example: { ru: "Вот я болван, удалил нужную папку.", en: "What a fool I am; I deleted the folder I needed." },
    source: "https://ru.wiktionary.org/wiki/болван",
  },
  {
    id: "podlets",
    word: "подле́ц",
    latin: "podlets",
    aliases: ["подлецы"],
    level: "rude",
    type: "insult",
    meaning: { en: "Scoundrel; rat", ru: "Человек, поступающий подло" },
    usage: {
      en: "Condemns dishonesty or betrayal rather than lack of intelligence.",
      ru: "Осуждает нечестность или предательство, а не недостаток ума.",
    },
    example: { ru: "Этот подлец свалил всю вину на коллегу.", en: "That rat put all the blame on a colleague." },
    source: "https://ru.wiktionary.org/wiki/подлец",
  },
  {
    id: "podonok",
    word: "подо́нок",
    latin: "podonok",
    aliases: ["подонки"],
    level: "rude",
    type: "insult",
    meaning: { en: "Scumbag; lowlife", ru: "Человек, вызывающий презрение и отвращение" },
    usage: {
      en: "A forceful condemnation of someone’s character or actions, without a mat root.",
      ru: "Резкое осуждение характера или поступков человека; матерного корня нет.",
    },
    example: { ru: "Подонок украл коробку с пожертвованиями.", en: "The scumbag stole the donation box." },
    source: "https://ru.wiktionary.org/wiki/подонок",
  },
  {
    id: "negodyay",
    word: "негодя́й",
    latin: "negodyay",
    aliases: ["негодяйка"],
    level: "rude",
    type: "insult",
    meaning: { en: "Scoundrel; villain", ru: "Подлый человек, вызывающий возмущение" },
    usage: {
      en: "A moral accusation that may sound theatrical in casual speech. Негодяйка is the feminine form.",
      ru: "Моральное осуждение; в бытовом разговоре может звучать театрально. Женская форма — «негодяйка».",
    },
    example: { ru: "Негодяй продал нам чужой велосипед.", en: "The scoundrel sold us someone else’s bicycle." },
    source: "https://ru.wiktionary.org/wiki/негодяй",
  },
  {
    id: "mraz",
    word: "мразь",
    latin: "mraz",
    aliases: [],
    level: "rude",
    type: "insult",
    meaning: { en: "Scum; a vile person", ru: "Презренный, отвратительный человек" },
    usage: {
      en: "A severe expression of contempt. Its grammatical feminine gender does not restrict who it describes.",
      ru: "Резкое выражение презрения. Грамматический женский род не ограничивает пол человека, о котором говорят.",
    },
    example: { ru: "Он назвал шантажиста мразью.", en: "He called the blackmailer scum." },
    source: "https://ru.wiktionary.org/wiki/мразь",
  },
  {
    id: "tvar",
    word: "тварь",
    latin: "tvar",
    aliases: ["твари"],
    level: "rude",
    type: "insult",
    meaning: { en: "Bastard; vile creature", ru: "Мерзкий, подлый человек" },
    usage: {
      en:
        "As an insult it expresses hostility and contempt. In older or religious writing it can simply mean ‘creature’.",
      ru:
        "Как оскорбление выражает враждебность и презрение. В старых или религиозных текстах может означать просто живое существо.",
    },
    example: { ru: "Какая тварь сломала скамейку?", en: "What bastard broke the bench?" },
    source: "https://ru.wiktionary.org/wiki/тварь",
  },
  {
    id: "skotina",
    word: "скоти́на",
    latin: "skotina",
    aliases: [],
    level: "rude",
    type: "insult",
    meaning: { en: "Swine; brute; bastard", ru: "Грубый, подлый человек" },
    usage: {
      en: "Literally livestock. As an insult it criticizes a person’s callous or disgraceful conduct.",
      ru: "Буквально — сельскохозяйственные животные. Как оскорбление осуждает грубость или низкие поступки человека.",
    },
    example: { ru: "Эта скотина нарочно испортила подарок.", en: "That swine deliberately ruined the present." },
    source: "https://ru.wiktionary.org/wiki/скотина",
  },
  {
    id: "ublyudok",
    word: "ублю́док",
    latin: "ublyudok",
    aliases: ["ублюдки"],
    level: "rude",
    type: "insult",
    meaning: { en: "Bastard; scumbag", ru: "Сильное презрительное оскорбление человека" },
    usage: {
      en: "Usually a general hostile insult. It need not make a literal claim about someone’s parentage.",
      ru:
        "Обычно общее враждебное оскорбление. Не обязательно связано с буквальным утверждением о происхождении человека.",
    },
    example: { ru: "Этот ублюдок подделал мою подпись.", en: "That bastard forged my signature." },
    source: "https://ru.wiktionary.org/wiki/ублюдок",
  },
  {
    id: "govnyuk",
    word: "говню́к",
    latin: "govnyuk",
    aliases: ["гавнюк"],
    level: "rude",
    type: "insult",
    meaning: { en: "Shithead; little shit", ru: "Неприятный или подлый человек" },
    usage: {
      en: "A vulgar personal insult derived from говно. Гавнюк is an informal phonetic spelling.",
      ru: "Вульгарное личное оскорбление от слова «говно». «Гавнюк» — неформальное написание по произношению.",
    },
    example: { ru: "Говнюк спрятал мой пропуск ради шутки.", en: "The little shit hid my pass as a joke." },
    source: "https://ru.wiktionary.org/wiki/говнюк",
  },
  {
    id: "dermo",
    word: "дерьмо́",
    latin: "dermo",
    aliases: [],
    level: "rude",
    type: "expression",
    meaning: { en: "Shit; crap; something worthless", ru: "Экскременты; что-то плохое или негодное" },
    usage: {
      en: "Used literally or as a contemptuous assessment of an object, work, or situation.",
      ru: "Употребляется буквально или как презрительная оценка предмета, работы или ситуации.",
    },
    example: {
      ru: "Купил дерьмо вместо нормального кабеля.",
      en: "I bought a piece of crap instead of a decent cable.",
    },
    source: "https://ru.wiktionary.org/wiki/дерьмо",
  },
  {
    id: "srat",
    word: "срать",
    latin: "srat",
    aliases: ["срал", "срут"],
    level: "rude",
    type: "verb",
    meaning: { en: "To shit", ru: "Испражняться — в грубой форме" },
    usage: {
      en: "A vulgar bodily verb. It also occurs in figurative expressions whose meaning depends on the phrase.",
      ru:
        "Вульгарный глагол о телесной функции. Встречается и в переносных выражениях со значением, зависящим от оборота.",
    },
    example: { ru: "Кот повадился срать в цветочный горшок.", en: "The cat has taken to shitting in the flowerpot." },
    source: "https://ru.wiktionary.org/wiki/срать",
  },
  {
    id: "zadolbatsya",
    word: "задолба́ться",
    latin: "zadolbatsya",
    aliases: ["задолбался", "задолбалась", "задолбались"],
    level: "rude",
    type: "verb",
    meaning: { en: "To get fed up; to wear oneself out", ru: "Устать, измучиться или прийти в раздражение" },
    usage: {
      en:
        "Describes the tired or irritated person. Compare задолбать, which describes causing that feeling in someone else.",
      ru: "Описывает состояние уставшего человека. «Задолбать» означает вызвать такое состояние у другого.",
    },
    example: { ru: "Я задолбался искать свободное место.", en: "I’m fed up with looking for a free space." },
    source: "https://ru.wiktionary.org/wiki/задолбаться",
  },
  {
    id: "zayebatsya",
    word: "заеба́ться",
    latin: "zayebatsya",
    aliases: ["заебался", "заебалась", "заебались"],
    level: "obscene",
    type: "verb",
    meaning: { en: "To be fucking exhausted; to get sick of something", ru: "Крайне устать или измучиться" },
    usage: {
      en: "Commonly expresses fatigue or frustration. Compare заебать ‘to wear someone out’ and заебись ‘great’.",
      ru: "Часто выражает усталость или раздражение. Сравните «заебать» — утомить другого и «заебись» — отлично.",
    },
    example: { ru: "Я заебался таскать эти коробки.", en: "I’m fucking exhausted from carrying these boxes." },
    source: "https://ru.wiktionary.org/wiki/заебаться",
  },
  {
    id: "vyyobyvatsya",
    word: "выёбываться",
    latin: "vyyobyvatsya",
    aliases: ["выёбываешься", "выёбывайся"],
    level: "obscene",
    type: "verb",
    meaning: { en: "To show off; to act like a smart-ass", ru: "Выпендриваться, выставлять себя напоказ" },
    usage: {
      en:
        "Criticizes ostentatious behavior or making something unnecessarily elaborate. Не выёбывайся is a hostile rebuke.",
      ru: "Осуждает показное поведение или ненужное усложнение. «Не выёбывайся» — грубый окрик.",
    },
    example: {
      ru: "Он выёбывается перед гостями с дорогими часами.",
      en: "He’s showing off his expensive watch to the guests like a smart-ass.",
    },
    source: "https://ru.wiktionary.org/wiki/выёбываться",
  },
  {
    id: "doyebatsya",
    word: "доеба́ться",
    latin: "doyebatsya",
    aliases: ["доебался", "доебалась", "доебались"],
    level: "obscene",
    type: "verb",
    meaning: { en: "To pick on; to hassle; to find fault", ru: "Придраться или настойчиво пристать" },
    usage: {
      en: "Often used with до or к plus the person or detail being targeted. It suggests unwelcome interference.",
      ru: "Часто с «до» или «к» и указанием человека либо детали. Подразумевает неприятное вмешательство.",
    },
    example: {
      ru: "Он доебался до одной запятой в письме.",
      en: "He made a fucking fuss over one comma in the letter.",
    },
    source: "https://ru.wiktionary.org/wiki/доебаться",
  },
  {
    id: "podyebat",
    word: "подъеба́ть",
    latin: "podyebat",
    aliases: ["подъебал", "подъебала", "подъебали"],
    level: "obscene",
    type: "verb",
    meaning: { en: "To take the piss out of; to needle", ru: "Подколоть, задеть насмешкой" },
    usage: {
      en: "Describes a pointed joke at someone’s expense. The relationship and tone determine how hostile it sounds.",
      ru: "О колкой шутке в чей-то адрес. Враждебность зависит от отношений и интонации.",
    },
    example: {
      ru: "Он решил подъебать меня насчёт моего опоздания.",
      en: "He decided to take the piss out of me for being late.",
    },
    source: "https://ru.wiktionary.org/wiki/подъебать",
  },
  {
    id: "obyebat",
    word: "объеба́ть",
    latin: "obyebat",
    aliases: ["объебал", "объебала", "объебали"],
    level: "obscene",
    type: "verb",
    meaning: { en: "To cheat; to screw someone over", ru: "Обмануть, облапошить" },
    usage: {
      en: "Emphasizes getting the better of someone through deception. Close in meaning to наебать.",
      ru: "Подчёркивает обман ради преимущества над другим. Близко по значению к «наебать».",
    },
    example: { ru: "Нас объебали при обмене денег.", en: "We got screwed over when we exchanged money." },
    source: "https://ru.wiktionary.org/wiki/объебать",
  },
  {
    id: "vyebat",
    word: "въеба́ть",
    latin: "vyebat",
    aliases: ["въебал", "въебали"],
    level: "obscene",
    type: "verb",
    meaning: { en: "To hit; to smack someone hard", ru: "Сильно ударить" },
    usage: {
      en: "An obscene verb for a blow. It can sound threatening when used about a future action against someone.",
      ru: "Матерный глагол об ударе. В высказывании о будущем действии в адрес человека может звучать как угроза.",
    },
    example: { ru: "В драке ему въебали по носу.", en: "He got fucking smacked in the nose in the fight." },
    source: "https://ru.wiktionary.org/wiki/въебать",
  },
  {
    id: "syebatsya",
    word: "съеба́ться",
    latin: "syebatsya",
    aliases: ["съебался", "съебалась", "съебались", "съебись"],
    level: "obscene",
    type: "verb",
    meaning: { en: "To get the fuck out; to clear off", ru: "Уйти, уехать или сбежать" },
    usage: {
      en: "An emphatic departure, sometimes to escape trouble. As a command it is an aggressive dismissal.",
      ru: "Резко выраженное действие ухода, иногда бегства от неприятностей. В приказе — агрессивная отсылка.",
    },
    example: {
      ru: "Мы съебались оттуда до начала драки.",
      en: "We got the fuck out of there before the fight started.",
    },
    source: "https://ru.wiktionary.org/wiki/съебаться",
  },
  {
    id: "razyebat",
    word: "разъеба́ть",
    latin: "razyebat",
    aliases: ["разъебал", "разъебала", "разъебали"],
    level: "obscene",
    type: "verb",
    meaning: { en: "To smash; to wreck; to tear someone apart verbally", ru: "Разбить, испортить; устроить разнос" },
    usage: {
      en: "Can describe physical damage, a severe scolding, or a crushing defeat. Context selects the sense.",
      ru: "Может обозначать повреждение, жёсткий выговор или разгромную победу. Смысл определяется контекстом.",
    },
    example: {
      ru: "Я разъебал экран, уронив телефон на плитку.",
      en: "I fucking smashed the screen by dropping my phone on the tiles.",
    },
    source: "https://ru.wiktionary.org/wiki/разъебать",
  },
  {
    id: "yeblan",
    word: "ебла́н",
    latin: "yeblan",
    aliases: ["ебланы"],
    level: "obscene",
    type: "insult",
    meaning: { en: "Fuckwit; asshole", ru: "Матерное презрительное оскорбление мужчины" },
    usage: {
      en: "Usually targets a man and expresses contempt, often for foolish or irritating behavior.",
      ru: "Обычно относится к мужчине и выражает презрение, часто из-за глупого или раздражающего поведения.",
    },
    example: { ru: "Какой еблан поставил кружку на клавиатуру?", en: "What fuckwit put a mug on the keyboard?" },
    source: "https://ru.wiktionary.org/wiki/еблан",
  },
  {
    id: "yebalo",
    word: "еба́ло",
    latin: "yebalo",
    aliases: ["ебалу", "ебалом"],
    level: "obscene",
    type: "expression",
    meaning: { en: "Face; mug, in very obscene language", ru: "Матерное название лица" },
    usage: {
      en: "A contemptuous word for the face. It makes otherwise ordinary remarks sound strongly insulting.",
      ru: "Презрительное обозначение лица. Делает даже обычное замечание резко оскорбительным.",
    },
    example: { ru: "У меня на фото такое сонное ебало.", en: "My fucking face looks so sleepy in that photo." },
    source: "https://ru.wiktionary.org/wiki/ебало",
  },
  {
    id: "pizdun",
    word: "пизду́н",
    latin: "pizdun",
    aliases: ["пиздуны"],
    level: "obscene",
    type: "insult",
    meaning: { en: "Bullshitter; liar; blabbermouth", ru: "Враль или болтун" },
    usage: {
      en: "An insult related to пиздеть, usually for a man whose talk is false or empty.",
      ru: "Оскорбление, связанное с «пиздеть»; обычно о мужчине, который врёт или много болтает.",
    },
    example: {
      ru: "Этот пиздун каждый раз придумывает новую отговорку.",
      en: "That bullshitter invents a new excuse every time.",
    },
    source: "https://ru.wiktionary.org/wiki/пиздун",
  },
  {
    id: "raspizdyay",
    word: "распиздя́й",
    latin: "raspizdyay",
    aliases: ["распиздяи"],
    level: "obscene",
    type: "insult",
    meaning: { en: "Irresponsible fuckup; slacker", ru: "Безответственный разгильдяй" },
    usage: {
      en: "Criticizes carelessness and lack of organization. Sometimes used jokingly, but still obscene.",
      ru: "Осуждает небрежность и неорганизованность. Иногда употребляется шутливо, но остаётся матерным словом.",
    },
    example: {
      ru: "Этот распиздяй опять забыл закрыть склад.",
      en: "That irresponsible fuckup forgot to lock the warehouse again.",
    },
    source: "https://ru.wiktionary.org/wiki/распиздяй",
  },
  {
    id: "yebuchy",
    word: "ебу́чий",
    latin: "yebuchy",
    aliases: ["ебучая", "ебучее", "ебучие"],
    level: "obscene",
    type: "expression",
    meaning: { en: "Fucking; goddamn; intensely annoying", ru: "Надоевший, досадный — в матерной форме" },
    usage: {
      en: "In complaints it intensifies annoyance at a person or thing, without a literal sexual meaning.",
      ru: "В жалобах усиливает раздражение человеком или предметом без буквального сексуального смысла.",
    },
    example: { ru: "Ебучий будильник не сработал.", en: "The goddamn alarm didn’t go off." },
    source: "https://ru.wiktionary.org/wiki/ебучий",
  },
  {
    id: "khuilo",
    word: "хуи́ло",
    latin: "khuilo",
    aliases: [],
    level: "obscene",
    type: "insult",
    meaning: { en: "Dickhead; asshole", ru: "Матерное презрительное название человека" },
    usage: {
      en: "A contemptuous insult derived from хуй. The word also has a literal anatomical sense.",
      ru: "Презрительное оскорбление, образованное от «хуй». У слова есть и буквальное анатомическое значение.",
    },
    example: { ru: "Какое-то хуило исписало стену лифта.", en: "Some dickhead scribbled all over the lift wall." },
    source: "https://ru.wiktionary.org/wiki/хуило",
  },
  {
    id: "khuyeta",
    word: "хуета́",
    latin: "khuyeta",
    aliases: [],
    level: "obscene",
    type: "expression",
    meaning: { en: "Crap; worthless or unpleasant stuff", ru: "Что-то некачественное, неприятное или тягостное" },
    usage: {
      en:
        "Dismisses the quality or value of something. Similar to хуйня, but the two are not interchangeable in every phrase.",
      ru: "Пренебрежительно оценивает качество или ценность. Близко к «хуйня», но не во всех оборотах взаимозаменяемо.",
    },
    example: { ru: "Новая ручка — хуета, сразу потекла.", en: "The new pen is crap; it leaked straight away." },
    source: "https://ru.wiktionary.org/wiki/хуета",
  },
  {
    id: "pizdaty",
    word: "пизда́тый",
    latin: "pizdaty",
    aliases: ["пиздатая", "пиздатое", "пиздато"],
    level: "obscene",
    type: "expression",
    meaning: { en: "Fucking great; excellent", ru: "Очень хороший, отличный" },
    usage: {
      en: "An obscene positive assessment. The related пиздато means something is going or looks great.",
      ru: "Матерная положительная оценка. Родственное «пиздато» означает, что всё идёт или выглядит отлично.",
    },
    example: { ru: "У тебя пиздатый новый рюкзак.", en: "Your new backpack is fucking great." },
    source: "https://ru.wiktionary.org/wiki/пиздатый",
  },
  {
    id: "nekhuyovy",
    word: "нехуёвый",
    latin: "nekhuyovy",
    aliases: ["нехуёвая", "нехуёвое", "нехуёво"],
    level: "obscene",
    type: "expression",
    meaning: { en: "Pretty fucking good; substantial", ru: "Неплохой; значительный по размеру или силе" },
    usage: {
      en: "Can praise quality or emphasize a large amount. A large amount is not necessarily welcome.",
      ru: "Может хвалить качество или подчёркивать большое количество. Большое количество не обязательно радует.",
    },
    example: { ru: "За ремонт выставили нехуёвый счёт.", en: "They sent us a pretty fucking hefty repair bill." },
    source: "https://ru.wiktionary.org/wiki/нехуёвый",
  },
  {
    id: "nikhuyasebe",
    word: "ни хуя́ себе́",
    latin: "ni khuya sebe",
    aliases: ["нихуя себе"],
    level: "obscene",
    type: "exclamation",
    meaning: { en: "Holy shit; fucking hell; no fucking way", ru: "Сильное удивление, восхищение или потрясение" },
    usage: {
      en:
        "An emotional reaction to something unexpected. The whole phrase has a different function from negative ни хуя.",
      ru: "Эмоциональная реакция на неожиданное. Целое выражение выполняет другую функцию, чем отрицательное «ни хуя».",
    },
    example: { ru: "Ни хуя себе, ты выиграл поездку!", en: "Holy shit, you won a trip!" },
    source: "https://ru.wiktionary.org/wiki/ни_хуя_себе",
  },
] satisfies CurseEntry[]).sort((a, b) => a.word.localeCompare(b.word, "ru"));

// Imported definitions retain source qualifiers. See curse-SOURCE.md for selection and licensing.
const letters: Record<string, string> = {
  а: "a",
  б: "b",
  в: "v",
  г: "g",
  д: "d",
  е: "e",
  ё: "yo",
  ж: "zh",
  з: "z",
  и: "i",
  й: "y",
  к: "k",
  л: "l",
  м: "m",
  н: "n",
  о: "o",
  п: "p",
  р: "r",
  с: "s",
  т: "t",
  у: "u",
  ф: "f",
  х: "kh",
  ц: "ts",
  ч: "ch",
  ш: "sh",
  щ: "shch",
  ъ: "'",
  ы: "y",
  ь: "'",
  э: "e",
  ю: "yu",
  я: "ya",
};
const readingAid = (word: string) =>
  [...word.replaceAll("\u0301", "")].map((letter) => letters[letter] ?? letter).join("");
const registerLabels: Record<string, Bilingual> = {
  vulgar: { en: "Vulgar", ru: "Вульгарное" },
  derogatory: { en: "Derogatory", ru: "Пренебрежительное" },
  offensive: { en: "Offensive", ru: "Оскорбительное" },
  slur: { en: "Slur", ru: "Уничижительное обозначение" },
  ethnic: { en: "Ethnic", ru: "Этническое" },
  slang: { en: "Slang", ru: "Сленг" },
  colloquial: { en: "Colloquial", ru: "Разговорное" },
  figuratively: { en: "Figurative", ru: "Переносное" },
  humorous: { en: "Humorous", ru: "Шутливое" },
  euphemistic: { en: "Euphemistic", ru: "Эвфемизм" },
  dated: { en: "Dated", ru: "Устаревающее" },
  archaic: { en: "Archaic", ru: "Устаревшее" },
  obsolete: { en: "Obsolete", ru: "Вышедшее из употребления" },
  historical: { en: "Historical", ru: "Историческое" },
  rare: { en: "Rare", ru: "Редкое" },
  dialectal: { en: "Dialectal", ru: "Диалектное" },
  Internet: { en: "Internet", ru: "Интернет" },
};
const importedWords: CurseEntry[] = dictionary.entries.map((entry) => {
  const tags = [...new Set(entry.senses.flatMap((sense) => sense.tags))];
  const labels = tags.filter((tag) => Object.hasOwn(registerLabels, tag));
  // Core mat roots; other vulgar and derogatory senses use the broader rude category.
  const mat = /пизд|ху[йеёяию]|(?:^|[аоуыьъ])(?:е|ё|йо)б|бляд/u.test(entry.lemma);
  return {
    id: `dict-${entry.lemma.replaceAll(" ", "_")}`,
    word: entry.word,
    latin: readingAid(entry.word),
    aliases: [],
    level: mat ? "obscene" : "rude",
    type: entry.pos === "verb" ? "verb" : entry.pos === "intj"
      ? "exclamation"
      : entry.pos === "noun" && tags.includes("derogatory")
      ? "insult"
      : "expression",
    meaning: { en: entry.senses.map((sense) => sense.gloss).join("; ") },
    usage: {
      en: labels.map((tag) => registerLabels[tag].en).join(" · "),
      ru: labels.map((tag) => registerLabels[tag].ru).join(" · "),
    },
    source: `https://en.wiktionary.org/wiki/${entry.lemma.replaceAll(" ", "_")}#Russian`,
    imported: true,
  };
});
export const curseWords: CurseEntry[] = [...curatedCurseWords, ...importedWords]
  .sort((a, b) => a.word.localeCompare(b.word, "ru"));
